### ISSUE TITLE
Drive: Won't drive backwards and turn simultaneously

### ISSUE THREAD

**Issue by szechy** [Team2337/2013-Ultimate-Ascent#17]
Last night during drive practice, the practice robot wouldn't drive backwards and turn simultaneously - some flaw in our Cheesy Drive? I'll assign myself for the day, but this will probably involve @silas13579 too.

**Comment by Tavaru5** [comment]
With whatever was implemented by @ColinSz  the bug seems to have vanished and we no longer have the problem of not being able to drive backwards and turn simultaneously. When I tested the code on my own, I noticed no error, so it may have been something with the drive constants (controls that Collin had me implement in order to not make too sharp of turns while at high speeds). Whatever the issue was, it is now fixed, although if any more bugs appear, we will dig deeper into the code to find it.
